version: "3.7"

services:
  phpfpm:
    build: docker/phpfpm
    container_name: phpfpm
    entrypoint: ./docker/phpfpm/entrypoint.sh
    restart: always
    volumes:
      - .:/var/www
      - ./docker/phpfpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    environment:
      WAIT: -wait tcp://phpfpm:9000
      TZ: America/Sao_Paulo
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - phpfpm

  db:
    build: docker/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=env_db
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - app-network


  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
